/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Fahim
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    Color DefaultColor,ClickedColor,HoverColor;
    private String uName;

  
    
    public Dashboard(String username) throws IOException {
        this.uName=username;
        initComponents();
        DefaultColor=new Color(54,33,89);
        ClickedColor=new Color(122,72,221);
        HoverColor=new Color(43,22,78);
        
        //to make the Home panel already selected as default when entered the dashboard 
        Home home1=new Home(uName);
        
        jDesktopPane.removeAll();
        jDesktopPane.add(home1).setVisible(true);

        //set default color to pan on run time
        HomeBut.setBackground(ClickedColor);
        TravelBut.setBackground(DefaultColor);
        HotelBut.setBackground(DefaultColor);
        ClockBut.setBackground(DefaultColor);
        EmergencyBut.setBackground(DefaultColor);
        CurrencyBut.setBackground(DefaultColor);
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TitleName = new javax.swing.JLabel();
        pictureBox1 = new com.raven.swing.PictureBox();
        jPanel6 = new javax.swing.JPanel();
        HomeBut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TravelBut = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        HotelBut = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ClockBut = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        EmergencyBut = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CurrencyBut = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jDesktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel SriLanka");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(122, 72, 221));

        jLabel4.setFont(new java.awt.Font("Yellowtail", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Travel Sri Lanka");

        TitleName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        TitleName.setForeground(new java.awt.Color(255, 255, 255));
        TitleName.setText("Home");

        pictureBox1.setImage(new javax.swing.ImageIcon("C:\\Users\\Fahim\\Documents\\NetBeansProjects\\Project\\Project\\src\\main\\java\\com\\mycompany\\project\\logo\\Elephant Logo.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(TitleName, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TitleName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(54, 33, 89));
        jPanel6.setToolTipText("");
        jPanel6.setPreferredSize(new java.awt.Dimension(208, 445));

        HomeBut.setBackground(new java.awt.Color(54, 33, 89));
        HomeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeButMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home");

        javax.swing.GroupLayout HomeButLayout = new javax.swing.GroupLayout(HomeBut);
        HomeBut.setLayout(HomeButLayout);
        HomeButLayout.setHorizontalGroup(
            HomeButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeButLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeButLayout.setVerticalGroup(
            HomeButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeButLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        TravelBut.setBackground(new java.awt.Color(54, 33, 89));
        TravelBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TravelButMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Travel Places");

        javax.swing.GroupLayout TravelButLayout = new javax.swing.GroupLayout(TravelBut);
        TravelBut.setLayout(TravelButLayout);
        TravelButLayout.setHorizontalGroup(
            TravelButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TravelButLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        TravelButLayout.setVerticalGroup(
            TravelButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TravelButLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        HotelBut.setBackground(new java.awt.Color(54, 33, 89));
        HotelBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HotelButMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hotels");

        javax.swing.GroupLayout HotelButLayout = new javax.swing.GroupLayout(HotelBut);
        HotelBut.setLayout(HotelButLayout);
        HotelButLayout.setHorizontalGroup(
            HotelButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HotelButLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HotelButLayout.setVerticalGroup(
            HotelButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HotelButLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        ClockBut.setBackground(new java.awt.Color(54, 33, 89));
        ClockBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClockButMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("World Clock");

        javax.swing.GroupLayout ClockButLayout = new javax.swing.GroupLayout(ClockBut);
        ClockBut.setLayout(ClockButLayout);
        ClockButLayout.setHorizontalGroup(
            ClockButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClockButLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ClockButLayout.setVerticalGroup(
            ClockButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClockButLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        EmergencyBut.setBackground(new java.awt.Color(54, 33, 89));
        EmergencyBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmergencyButMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Emergency");

        javax.swing.GroupLayout EmergencyButLayout = new javax.swing.GroupLayout(EmergencyBut);
        EmergencyBut.setLayout(EmergencyButLayout);
        EmergencyButLayout.setHorizontalGroup(
            EmergencyButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmergencyButLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmergencyButLayout.setVerticalGroup(
            EmergencyButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmergencyButLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        CurrencyBut.setBackground(new java.awt.Color(54, 33, 89));
        CurrencyBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CurrencyButMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Currency");

        javax.swing.GroupLayout CurrencyButLayout = new javax.swing.GroupLayout(CurrencyBut);
        CurrencyBut.setLayout(CurrencyButLayout);
        CurrencyButLayout.setHorizontalGroup(
            CurrencyButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrencyButLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CurrencyButLayout.setVerticalGroup(
            CurrencyButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrencyButLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TravelBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomeBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HotelBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CurrencyBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmergencyBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClockBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(HomeBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TravelBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HotelBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClockBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmergencyBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CurrencyBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jDesktopPane.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane.setPreferredSize(new java.awt.Dimension(784, 440));
        jDesktopPane.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TravelButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TravelButMousePressed
        // TODO add your handling code here:
        HomeBut.setBackground(DefaultColor);
        TravelBut.setBackground(ClickedColor);
        HotelBut.setBackground(DefaultColor);
        ClockBut.setBackground(DefaultColor);
        EmergencyBut.setBackground(DefaultColor);
        CurrencyBut.setBackground(DefaultColor);
        
        TitleName.setText("Travel Places");
        
        Travel travel1=new Travel();
        jDesktopPane.removeAll();
        jDesktopPane.add(travel1).setVisible(true);
    }//GEN-LAST:event_TravelButMousePressed

    private void HotelButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HotelButMousePressed
        // TODO add your handling code here:
        HomeBut.setBackground(DefaultColor);
        TravelBut.setBackground(DefaultColor);
        HotelBut.setBackground(ClickedColor);
        ClockBut.setBackground(DefaultColor);
        EmergencyBut.setBackground(DefaultColor);
        CurrencyBut.setBackground(DefaultColor);
        
        TitleName.setText("Hotels");
        
        Hotels hotels1=new Hotels();
        jDesktopPane.removeAll();
        jDesktopPane.add(hotels1).setVisible(true);
    }//GEN-LAST:event_HotelButMousePressed

    private void ClockButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClockButMousePressed
        // TODO add your handling code here:
        HomeBut.setBackground(DefaultColor);
        TravelBut.setBackground(DefaultColor);
        HotelBut.setBackground(DefaultColor);
        ClockBut.setBackground(ClickedColor);
        EmergencyBut.setBackground(DefaultColor);
        CurrencyBut.setBackground(DefaultColor);
        
        TitleName.setText("World Clock");
        
        Clock clock1=new Clock();
        jDesktopPane.removeAll();
        jDesktopPane.add(clock1).setVisible(true);
    }//GEN-LAST:event_ClockButMousePressed

    private void EmergencyButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmergencyButMousePressed
        // TODO add your handling code here:
        HomeBut.setBackground(DefaultColor);
        TravelBut.setBackground(DefaultColor);
        HotelBut.setBackground(DefaultColor);
        ClockBut.setBackground(DefaultColor);
        EmergencyBut.setBackground(ClickedColor);
        CurrencyBut.setBackground(DefaultColor);
        
        TitleName.setText("Emergency Services");
        
        Emergency emergency1=new Emergency();
        jDesktopPane.removeAll();
        jDesktopPane.add(emergency1).setVisible(true);
    }//GEN-LAST:event_EmergencyButMousePressed

    private void CurrencyButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurrencyButMousePressed
        // TODO add your handling code here:
        HomeBut.setBackground(DefaultColor);
        TravelBut.setBackground(DefaultColor);
        HotelBut.setBackground(DefaultColor);
        ClockBut.setBackground(DefaultColor);
        EmergencyBut.setBackground(DefaultColor);
        CurrencyBut.setBackground(ClickedColor);
        
        TitleName.setText("Currency Converter");
        
        Currency currency1=new Currency();
        jDesktopPane.removeAll();
        jDesktopPane.add(currency1).setVisible(true);
    }//GEN-LAST:event_CurrencyButMousePressed

    private void HomeButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButMousePressed
        // TODO add your handling code here:
        HomeBut.setBackground(ClickedColor);
        TravelBut.setBackground(DefaultColor);
        HotelBut.setBackground(DefaultColor);
        ClockBut.setBackground(DefaultColor);
        EmergencyBut.setBackground(DefaultColor);
        CurrencyBut.setBackground(DefaultColor);
        
        TitleName.setText("Home");
        
        Home home1;
        try {
            home1 = new Home(uName);
            jDesktopPane.removeAll();
            jDesktopPane.add(home1).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_HomeButMousePressed

    
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new Dashboard().setVisible(true);
            }
        });
        //new Dashboard().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClockBut;
    private javax.swing.JPanel CurrencyBut;
    private javax.swing.JPanel EmergencyBut;
    private javax.swing.JPanel HomeBut;
    private javax.swing.JPanel HotelBut;
    private javax.swing.JLabel TitleName;
    private javax.swing.JPanel TravelBut;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private com.raven.swing.PictureBox pictureBox1;
    // End of variables declaration//GEN-END:variables
}
